export const feedbackMessages = {
    group: {
        createSuccess: "Le groupe a été créé avec succès.",
        createError: "Impossible de créer le groupe.",
        emptyDescription: "La description du groupe est obligatoire.",
        emptyName: "Le nom du groupe est obligatoire.",
    },
    document: {
        renameSelected: "Aucun document a renommer n'est séléctionné.",
        renameSuccess: "Le document a bien été renommé.",
        renameError: "Impossible de renommer le document.",
        emptyName: "Le nom du document ne peut pas être vide.",
        deleteSelected: "Aucun document sélectionné pour la suppression.",
        deleteSuccess: "Le document a bien été supprimé.",
        deleteError: "Impossible de supprimer le document.",
        shareSuccess: "Le document a bien été partagé.",
        shareError: "Impossible de partager le document.",
        shareSelected: "Aucun document séléctionné a partager.",
        shareUsers: "Veuillez selectionner au moins un utilisateur.",
        downloadError: "Impossible de trouver le document a télécharger.",
        downloadSuccess: "Le téléchargement du document à commencé.",
    },
    profile: {
        updateSuccess: "Le profil a été mis à jour avec succès.",
        updateError: "Impossible de mettre à jour le profil.",
        deleteSuccess: "Le profil a été supprimé.",
        deleteError: "Impossible de supprimer le profil.",
        emailValidate: "Veuillez entrer une adresse email valide.",
        emailObligatory: "L'email est obligatoire.",
        phoneObligatory: "Le numéro de téléphone est obligatoire.",
        adressObligatory: "L'adresse est obligatoire.",
        photoType: "Format invalide. Utilisez PNG, JPG ou WEBP.",
        photoSize: "L'image dépasse la taille maximale de 5 Mo.",
        photoSelected: "Veuillez sélectionner une image.",
        photoSuccess: "La photo de profil a été mise à jour avec succès.",
    },
    password: {
        emptyPassword: "Veuillez remplir tous les champs.",
        passwordLength: "Le nouveau mot de passe doit contenir au moins 8 caractères.",
        passwordConfirm: "La confirmation du mot de passe ne correspond pas.",
        passwordSuccess: "Le mot de passe a été modifié avec succès.",
        passwordError: "Une erreur est survenue.",
    }
};